[로그인] API
f-lab-edu/GitHub-Repo pull request #5
Opened 2024-07-08 17:07 UTC by GongDoMin

- [feat] api & response model 생성
- [feat] OkHttpClient & Retrofit & gitHubTokenApiService DI 설정
- [feat] dataSource & dataSourceImpl & dto 생성
- [feat] dataSoruce DI 설정
- [feat] repository & repositoryImpl & entity 생성
- [feat] repository DI 설정

2024-07-08 17:26 UTC, bigstark requested changes
새벽까지 고생 많으셨습니다 도민님!

전반적으로 singleton component 에 singleton 으로 제공을 하고 있습니다. 지금 당장은 어색하지는 않습니다만, 용도에 따라 명확하게 스코프를 제공하는 것을 고민해보시면 좋을 것 같습니다. 예를 들어 Repository 가 singleton 으로 제공되고 있다면 하위의 data source 가 singleton 일 필요는 없어보여요. data source 는 단순히 정보를 IO 하는 역할에 집중되는 것이기 때문에 굳이 singleton 으로 정의될 필요도 없을 것 같구요!

2024-07-08 17:26 UTC, bigstark commented on data/src/main/java/com/prac/data/di/RetrofitModule.kt
> +            .build()
OkHttpClient 의 설정값들도 추가해주셨으면 좋겠어요! 
connect / read / write timeout 시간이라든가, request interceptor 등이요!

2024-07-08 17:26 UTC, bigstark commented on data/src/main/java/com/prac/data/di/RetrofitModule.kt
> +            .baseUrl("https://github.com/")
실 프로덕트에서는 빌드 타입이나 product flavor 에 따라  base url 이 변경될 수 있어요. 
build config 를 통해서 url 을 설정할 수 있는 방법을 찾아보시면 좋을 것 같아요!

2024-07-08 17:26 UTC, bigstark commented on data/src/main/java/com/prac/data/di/RetrofitModule.kt
> +                Json.asConverterFactory("application/json".toMediaType())
serialization 의 다양한 기능들 (eg, polymorphism)을 사용하려면 해당 factory 도 주입받는 형태로 있으면 조금 더 확장성 있는 구조가 될 것 같네요!

2024-07-08 17:26 UTC, bigstark commented on data/src/main/java/com/prac/data/repository/GetAccessTokenRepository.kt
> +    ) : Flow<AccessTokenEntity>
Flow 로 정의하는 이유가 혹시 있을까요? access token 가 변경되는 것을 어디선가 구독해야하나요?

2024-07-08 17:26 UTC, bigstark commented on data/src/main/java/com/prac/data/source/api/GitHubTokenApi.kt
> +    ): Response<AccessTokenModel>
kotlin 사용하실 예정이니, suspend fun 으로 변경하는 것은 어떨까요?
```suggestion
    @POST("login/oauth/access_token")
    suspend fun getAccessToken(
        @Header("Accept") accept: String = "application/json",
        @Query("client_id") clientID: String,
        @Query("client_secret") clientSecret: String,
        @Query("code") code: String,
    ): AccessTokenModel
```

2024-07-08 17:26 UTC, bigstark commented on data/src/main/java/com/prac/data/source/impl/GetAccessTokenDataSourceImpl.kt
> +            throw e
에러는 명확하게 정의되는 편이 좋을 것 같네요. IOException 을 정의하여 던지는 것은 불명확한 것 같습니다!

2024-07-08 17:26 UTC, bigstark commented on data/src/main/java/com/prac/data/source/model/AccessTokenModel.kt
> +    val token_type: String
필드에 snake case 는 용납되지 않습니닷!

2024-07-08 17:26 UTC, bigstark commented on data/src/main/java/com/prac/data/source/model/AccessTokenModel.kt
> +    val token_type: String
https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization/-serial-name/

2024-07-08 17:26 UTC, bigstark commented on data/src/main/java/com/prac/data/repository/GetAccessTokenRepository.kt
> +interface GetAccessTokenRepository {
Repository 는 조금 더 범용으로 정의되면 좋을 것 같아요. 추후 access token 을 가져오는 역할만 하지는 않을 것으로 보입니다.

2024-07-09 02:15 UTC, GongDoMin commented on data/src/main/java/com/prac/data/repository/GetAccessTokenRepository.kt
> +    ) : Flow<AccessTokenEntity>
viewModel에서 데이터 변화를 감지하기 위해 Hot Flow를 사용할 예정이었습니다. 그래서 Data Module에서 Cold Flow를 받아와서 Flow 확장함수를 통해서 Hot Flow로 변경하고자 사용했습니다.

2024-07-09 02:55 UTC, GongDoMin commented on data/src/main/java/com/prac/data/repository/GetAccessTokenRepository.kt
> +    ) : Flow<AccessTokenEntity>
viewModel에서 데이터 변화를 감지하기 위해 Hot Flow를 사용할 예정이었습니다. 그래서 Data Module에서 Cold Flow를 받아와서 Flow 확장함수를 통해서 Hot Flow로 변경하고자 사용했습니다. 

다시 코드를 보니 Flow가 아니어도 충분히 구현가능하며 오히려 데이터 스트림 처리를 하기 위한 Flow의 다양한 함수들을 사용하지 않고  Flow로 래핑하는건 메모리 측면에서 비효율적인 것 같습니다.

2024-07-14 03:37 UTC, bigstark approved these changes
수고많으셨어요! 수정할 사항이 없는 것은 아니지만, 일단 머지 하시죠!

2024-07-14 03:37 UTC, bigstark commented on data/src/main/java/com/prac/data/source/GetAccessTokenApiDataSource.kt
> +    ) : AccessTokenDto
요 data source 도 repository 와 마찬가지로 조금 더 범용으로 설계되면 좋을 것 같습니닷!

2024-07-14 03:37 UTC, bigstark commented on data/src/main/java/com/prac/data/di/RetrofitModule.kt
> +            .baseUrl(BuildConfig.GITHUB_URL)
p4; 규모가 커지다보면 여러 종류의 base url 을 사용하게되는 경우도 존재합니다. 그럴 때를 위해 base url 도 주입받을 수 있도록 설계가 되면 더욱 더 좋습니다.

2024-07-14 03:37 UTC, bigstark commented on data/src/main/java/com/prac/data/source/model/AccessTokenModel.kt
> +)
요친구가 AccessTokenDto 가 되어야할 것 같네요!

2024-07-14 03:37 UTC, bigstark commented on data/src/main/java/com/prac/data/source/api/ErrorHandleInterceptor.kt
> +            401 -> {
p4; 요런 에러 코드같은 경우 const 로 정의되는 편이 좋습니다.

2024-07-14 03:37 UTC, bigstark commented on data/src/main/java/com/prac/data/source/api/ErrorHandleInterceptor.kt
> +        }
또한 이부분은 응답에 관련된 부분이기 때문에 interceptor 의 역할로서는 맞지는 않은 것 같아요. interceptor 를 계속 추가하는 경우도 발생하구요.

Retrofit 의 [CallAdapter](https://square.github.io/retrofit/2.x/retrofit/retrofit2/CallAdapter.html) 같은 놈을 통해 error handling 을 하는 것이 조금 더 바람직해 보입니다!

2024-07-14 05:56 UTC, GongDoMin commented on data/src/main/java/com/prac/data/source/api/ErrorHandleInterceptor.kt
> +        }
넵 참고해보겠습니다!

2024-07-14 05:56 UTC, merged